config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "home#home"
  get "signup", to:"users#signup"

  get "login", to: "session#new"
  post "login", to:"session#create"

  get "logout", to: "session#destroy"

  get  'chatroom', to:"chatroom#index"
  post 'message', to:"messages#create"

  mount ActionCable.server, at: '/cable'

  

  resources :users, except:[:new]



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :user
	validates :body, presence:true, length:{minimum:2, maximum:100}
	validates :user_id, presence:true


end

app/models/user.rb
class User < ApplicationRecord
	has_many :messages
	validates :username , presence: true, uniqueness:{case_sensitive:false}, length:{minimum:5, maximum:50}
	VALID_EMAIL_REGEX=  /\w+?@\w+?\x2E.+/
	validates :email, presence: true, uniqueness:{case_sensitive: false}, length:{minimum: 5, maximum: 50}, format: {with: VALID_EMAIL_REGEX } 


	has_secure_password 



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :current_user, :logged_in

	def current_user

		@current_user ||= User.find(session[:user_id]) if session[:user_id]

	end


	def logged_in


		!!current_user

	end


	def require_user

		if !logged_in
			flash[:notice]="You Must log in to Use this feature"

			redirect_to root_path

		end

	end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
	protect_from_forgery :except => [:index]

	before_action :require_user
	def index
		@messages=Message.all
		@message=Message.new
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController





	def home

	end



end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	protect_from_forgery :except => [:message_params,:message_render,:create]

	before_action :require_user


	def create

		message=current_user.messages.build(message_params)

		if message.save
			ActionCable.server.broadcast "chatroom_channel", msg:message_render(message)
			#redirect_to chatroom_path
		end

	end

	private
	 def message_params
		params.require(:message).permit(:body)
	end

	def message_render(message)
		render(partial: 'message', locals:{message: message})
	end
















end

app/controllers/session_controller.rb
class SessionController < ApplicationController


	protect_from_forgery :except => [:new,:create,:destroy]

	def new

	end

	def create
		user=User.find_by(email: params[:session][:email])

		if user && user.authenticate(params[:session][:password])
			flash[:positive]="You have logged in!"
			session[:user_id]=user.id
			redirect_to chatroom_path

		else

			flash.now[:negative]="There is something wrong with your info"
			render 'new'

		end

	end

	def destroy
		session[:user_id]= nil
		redirect_to root_path

	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController



	protect_from_forgery :except => [:signup,:create,:index,:user_params]

	def signup
		@users=User.new
	end

	def create
		@users=User.create(user_params)

		if @users.save

			flash[:positive]="You have succesfully created an account, Now Login using ur email and password!"

			redirect_to root_path
			else

				render 'signup'
		end

	end

	def index

		@users=User.all
	end

	def user_params
		params.require(:user).permit(:username,:email, :password)

	end



end

app/helpers/application_helper.rb
module ApplicationHelper

	
end

app/views/chatroom/index.html.erb
<div class="ui grid fluid ">

  <div class="sixteen wide stretched column" style="height: 1200px; ">

      <div class="ui segment"  id="message-box" >
        <%= render @messages %>
      </div>



    <div>
      <%= form_for(@message , url:message_path, remote:true, authenticity_token: true) do |f|  %>
      <div class="ui fluid  input" style="height: 50px;">
      <%= f.text_field :body ,placeholder:"enter message" %>
      <%= f.button "Send", class: "ui inverted red  right floated button".html_safe %>
      </div>
      <% end %>
    </div>





  </div>


</div>

app/views/home/home.html.erb
<div class="home eight wide column">
  <h1>Acme-Messaging</h1>





    <div class="ui buttons stackable four column grid" id="buttons">
      <%= link_to "SignUP", signup_path, class: "massive ui inverted yellow button"%>
      <div class="or"></div>
      <%= link_to "Login", login_path, class: "massive ui inverted yellow button" %>
    </div>


</div>

app/views/layouts/_errors.html.erb
<% if @user %>

	<% @user.errors.full_messages.each do |e| %>


	<ul>
		<li><a><%= e %></a></li>
	</ul>

	<% end %>



<% end %>

app/views/layouts/_msg.html.erb
<% flash.each do |name,msg| %>

<div class="ui #{name} message">
  <i class="close icon"></i>
  <div class="header">
    <%= msg %>
  </div>
</div>


<% end  %>

app/views/layouts/_navbar.html.erb
<% if logged_in %>
<div class="ui    menu">


  <%= link_to "Chat", chatroom_path, class: "item" %>


  <%= link_to "Acme-Users", users_path, class: "red item" %>


<% end %>



<% if logged_in %>

  <div class="right menu">

    <a class="ui teal tag label"><%= current_user.username.capitalize %></a>
    <%= link_to "Logout", logout_path, class: " ui item", method: :delete %>
  </div>

</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AcmeMessaging</title>
    <%= action_cable_meta_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>


  <div class="ui two column doubling stackable  container">

    <%= render 'layouts/navbar' %>
    <%= render 'layouts/errors' %>
    <%= yield %>



     </div>

  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
       <div class="content">
               <div class="summary" >
                      <a><%= message.user.username %>: </a> <em><%= message.body %></em>
               </div>
        </div>

</div>

app/views/session/new.html.erb
<h1>Login</h1>
<%= form_for(:session, url:login_path) do |f|  %>
<div class="ui placeholder segment">
  <div class="ui two column very relaxed stackable grid">
    <div class="column">
      <div class="ui form">
        </div>
        <div class="field">
          <label>Email</label>
          <div class="ui  input">
            <%= f.text_field :email, class: "ui  input" %>
          </div>
        </div>
        <div class="field">
          <label>Password</label>
          <div class="ui  input">
            <%= f.password_field :password, class: "ui  input"%>
          </div>
        </div>
        <%= f.submit "Login", class: "submit-button ui blue submit button" %>
      </div>
    </div>
    
  </div>


<% end %>

app/views/users/index.html.erb
<%  @users.each do |user| %>

<div class="ui divided selection list">
  <a class="item">
    <div class="ui red horizontal label"><%= user.username.capitalize %></div>
  </a>
</div>


<% end %>

app/views/users/signup.html.erb
<h1>Sign-Up</h1>
<%= form_for @users do |f|  %>
<%= token_tag(nil) %>
<div class="ui placeholder segment">
  <div class="ui two column very relaxed stackable grid">
    <div class="column">
      <div class="ui form">
        <div class="field">
          <label>Username</label>
          <div class="ui left icon input">
            <%= f.text_field :username, class: "ui left icon input" %>
          </div>
        </div>
        <div class="field">
          <label>Email</label>
          <div class="ui left icon input">
            <%= f.text_field :email, class: "ui left icon input" %>
          </div>
        </div>
        <div class="field">
          <label>Password</label>
          <div class="ui left icon input">
            <%= f.password_field :password, class: "ui left icon input"%>

          </div>
        </div>
        <%= f.submit "Sign-Up", class: "submit-button ui blue submit button" %>
      </div>
    </div>

  </div>

</div>

<% end %>